### ISSUE TITLE
goole打不开

### ISSUE THREAD

**Issue by LN-111** [AsherShelby/FuckingOnlineCourse#2]
大佬我为啥执行了这个程序，chrom浏览器不自己打开，没效果，是浏览器版本不对吗

**Comment by AsherShelby** [comment]
试试去这里下载你Chrome浏览器对应版本的驱动 https://googlechromelabs.github.io/chrome-for-testing/

替换安装目录里的chromedriver就行

**Comment by LN-111** [comment]
> 试试去这里下载你Chrome浏览器对应版本的驱动 https://googlechromelabs.github.io/chrome-for-testing/
> 
> 替换安装目录里的chromedriver就行

我现在尝试执行代码，
程序尝试加载位于 '/Users/yun/Downloads/FuckingOnlineCourse-2.2/assets/icons8_settings_24px.png' 的图像文件，但是该文件似乎不存在
下面是报错图![image](https://github.com/AsherShelby/FuckingOnlineCourse/assets/85479940/11e484d3-d0e0-489d-8740-c9bc6b25be6b)

**Comment by LN-111** [comment]
Traceback (most recent call last):
  File "/Users/yun/Downloads/FuckingOnlineCourse-2.2/app.py", line 17, in <module>
    mainWindow = MainFrame(window)
  File "/Users/yun/Downloads/FuckingOnlineCourse-2.2/MainWindow.py", line 60, in __init__
    self.photoimages.append(ImageTk.PhotoImage(name=key, file=_path))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/ImageTk.py", line 102, in __init__
    image = _get_image_from_kw(kw)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/ImageTk.py", line 59, in _get_image_from_kw
    return Image.open(source)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yun/Downloads/FuckingOnlineCourse-2.2\\assets\\icons8_settings_24px.png'
Exception ignored in: <function PhotoImage.__del__ at 0x105a200d0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/ImageTk.py", line 132, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'

**Comment by AsherShelby** [comment]
> > 试试去这里下载你Chrome浏览器对应版本的驱动 https://googlechromelabs.github.io/chrome-for-testing/
> > 替换安装目录里的chromedriver就行
> 
> 我现在尝试执行代码， 程序尝试加载位于 '/Users/yun/Downloads/FuckingOnlineCourse-2.2/assets/icons8_settings_24px.png' 的图像文件，但是该文件似乎不存在 下面是报错图![image](https://private-user-images.githubusercontent.com/85479940/331446439-11e484d3-d0e0-489d-8740-c9bc6b25be6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjEyOTAsIm5iZiI6MTcxNTkyMDk5MCwicGF0aCI6Ii84NTQ3OTk0MC8zMzE0NDY0MzktMTFlNDg0ZDMtZDBlMC00ODlkLTg3NDAtYzliYzZiMjViZTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNmYyNTM0M2I1NDYzZGRiYzNlMzI1Yzk0N2MyMThlZDEyOTc2MDgzMzUyOTc2ZDRkNGYzNmEwMWZiZDdiNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5d74OPWNGo-T17ldRjre7j8L52kKpGaUTAKOWuhcqr0)

你是Linux环境吗？我这边的测试环境是Windows，稍等一下，我修改下代码

**Comment by LN-111** [comment]
> > > 试试去这里下载你Chrome浏览器对应版本的驱动 https://googlechromelabs.github.io/chrome-for-testing/
> 
> > > 替换安装目录里的chromedriver就行
> 
> > 
> 
> > 我现在尝试执行代码， 程序尝试加载位于 '/Users/yun/Downloads/FuckingOnlineCourse-2.2/assets/icons8_settings_24px.png' 的图像文件，但是该文件似乎不存在 下面是报错图![image](https://private-user-images.githubusercontent.com/85479940/331446439-11e484d3-d0e0-489d-8740-c9bc6b25be6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjEyOTAsIm5iZiI6MTcxNTkyMDk5MCwicGF0aCI6Ii84NTQ3OTk0MC8zMzE0NDY0MzktMTFlNDg0ZDMtZDBlMC00ODlkLTg3NDAtYzliYzZiMjViZTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNmYyNTM0M2I1NDYzZGRiYzNlMzI1Yzk0N2MyMThlZDEyOTc2MDgzMzUyOTc2ZDRkNGYzNmEwMWZiZDdiNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5d74OPWNGo-T17ldRjre7j8L52kKpGaUTAKOWuhcqr0)
> 
> 
> 
> 你是Linux环境吗？我这边的测试环境是Windows，稍等一下，我修改下代码

是的大佬 我是mac， 那个exe程序我换了匹配版本chromedriver在win上执行还是没反应

**Comment by AsherShelby** [comment]
代码已经更新，刚才的报错似乎是Linux环境下的路径分隔符问题，由于我这台pc还没装虚拟机，测试不了Linux环境，如果有问题还请你及时反馈

**Comment by AsherShelby** [comment]
> > > > 试试去这里下载你Chrome浏览器对应版本的驱动 https://googlechromelabs.github.io/chrome-for-testing/
> > 
> > 
> > > > 替换安装目录里的chromedriver就行
> > 
> > 
> > > 
> > 
> > 
> > > 我现在尝试执行代码， 程序尝试加载位于 '/Users/yun/Downloads/FuckingOnlineCourse-2.2/assets/icons8_settings_24px.png' 的图像文件，但是该文件似乎不存在 下面是报错图![image](https://private-user-images.githubusercontent.com/85479940/331446439-11e484d3-d0e0-489d-8740-c9bc6b25be6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjEyOTAsIm5iZiI6MTcxNTkyMDk5MCwicGF0aCI6Ii84NTQ3OTk0MC8zMzE0NDY0MzktMTFlNDg0ZDMtZDBlMC00ODlkLTg3NDAtYzliYzZiMjViZTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNmYyNTM0M2I1NDYzZGRiYzNlMzI1Yzk0N2MyMThlZDEyOTc2MDgzMzUyOTc2ZDRkNGYzNmEwMWZiZDdiNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5d74OPWNGo-T17ldRjre7j8L52kKpGaUTAKOWuhcqr0)
> > 
> > 
> > 你是Linux环境吗？我这边的测试环境是Windows，稍等一下，我修改下代码
> 
> 是的大佬 我是mac， 那个exe程序我换了匹配版本chromedriver在win上执行还是没反应

![image](https://github.com/AsherShelby/FuckingOnlineCourse/assets/94681217/a85d75e2-e5b1-40f3-80ba-e1d09f7d477d)
FuckOnlineCourse.py 的initial函数里可以修改chromedriver的路径，驱动不匹配的话会报错，
![image](https://github.com/AsherShelby/FuckingOnlineCourse/assets/94681217/9216b360-c346-4469-85fa-97582e220c98)
会告诉你当前驱动支持的浏览器版本

**Comment by AsherShelby** [comment]
exe执行文件出错的原因正在排查

**Comment by AsherShelby** [comment]
找到原因了，打包的时候目录结构似乎不一样，回到安装目录，新建一个bin目录，把chromedriver和common.onx，放进bin目录里就行
![image](https://github.com/AsherShelby/FuckingOnlineCourse/assets/94681217/33b150d0-9f39-4a38-aaa7-a7ee7af29e0e)

**Comment by LN-111** [comment]
> 代码已经更新，刚才的报错似乎是Linux环境下的路径分隔符问题，由于我这台pc还没装虚拟机，测试不了Linux环境，如果有问题还请你及时反馈

好的大佬已经可以用了真的太谢谢你了，但是他好像不能选择课程，我第一节的课是尚未开始的，他只能重复点进去，并不能看别的

**Comment by LN-111** [comment]
> > 代码已经更新，刚才的报错好像是Linux环境下的路径分区符问题，由于我这台电脑还没有安装虚拟机，测试不了Linux环境，如果有问题还请您及时反馈
> 
> 好的大佬已经可以用了真的太谢谢你了，但是他想不能选择课程，我第一节的课还没开始的，他只能重复点进去，并不能看别的

![微信图片_20240517134409](https://github.com/AsherShelby/FuckingOnlineCourse/assets/85479940/40ab2ad8-e2af-4e26-9ada-50a619d44a83)

**Comment by LN-111** [comment]
> > > 代码已经更新，刚才的报错好像是Linux环境下的分区符问题，由于我这台电脑还没有安装虚拟机，测试不了Linux环境，如果有问题还请您及时反馈
> > 
> > 
> > 好的大佬已经可以用了真的太谢谢你了，但是他想不能选择课程，我第一节的课还没开始的，他只能重复点进去，并不能看别的
> 
> ![微信图片_20240517134409](https://private-user-images.githubusercontent.com/85479940/331472546-40ab2ad8-e2af-4e26-9ada-50a619d44a83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjQ5NzAsIm5iZiI6MTcxNTkyNDY3MCwicGF0aCI6Ii84NTQ3OTk0MC8zMzE0NzI1NDYtNDBhYjJhZDgtZTJhZi00ZTI2LTlhZGEtNTBhNjE5ZDQ0YTgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA1NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZWZhM2IzMmQ0YjE4YTE3MjAyNGM1ZWFjODM1ZjQzYzE5NmU4MGNlMGJjYWE2NDk1NmE3ZjBkYjVlZDAzOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gEKcyFDnvYXDqh0kHqq9TtpuiwSc1d_GzpliOKqBMq8)

就一直停在这里了

**Comment by AsherShelby** [comment]
这个“尚未开始”能点进去吗

**Comment by LN-111** [comment]
> 这个“尚未开始”能点进去吗
> 
> 

点不进去的

**Comment by AsherShelby** [comment]
啊这，那你们学校应该还没开放这个课程吧？不能被点击的话看不了，因为这个程序是基于自动化操作的

**Comment by LN-111** [comment]
> 啊这，那你们学校应该还没开放这个课程吧？不能被点击的话看不了，因为这个程序是基于自动化操作的
不能换一门课嘛，只能让他自己来吗

**Comment by LN-111** [comment]
> > 啊这，那你们学校应该还没开放这个课程吧？不能被点击的话看不了，因为这个程序是基于自动化操作的
> > 不能换一门课嘛，只能让他自己来吗？

因为那个是线下课，这个不能想办法跳过那一个吗大佬

**Comment by AsherShelby** [comment]
是可以的，我设定的逻辑是从上往下找到第一个没刷满的课程，没有考虑还未开放的课程😂
![image](https://github.com/AsherShelby/FuckingOnlineCourse/assets/94681217/058aaf17-c96b-47fd-bc08-e224e27f3356)
如果你懂python的话，可以自行修改一下，我可能需要等会才能继续修

**Comment by LN-111** [comment]
> 是可以的，我设定的逻辑是从上往下找到第一个未满的课程，没有开放的课程😂 如果你懂修改刷python的话，可以自行一下，我可能需要等会才能继续修改 ![图像](https://private-user-images.githubusercontent.com/94681217/331475005-058aaf17-c96b-47fd-bc08-e224e27f3356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjY0NDYsIm5iZiI6MTcxNTkyNjE0NiwicGF0aCI6Ii85NDY4MTIxNy8zMzE0NzUwMDUtMDU4YWFmMTctYzk2Yi00N2ZkLWJjMDgtZTIyNGUyN2YzMzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA2MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYzcwM2IzZjI0ZDIwOTc3MThjMzAyNmIwYTEwMjhiYzExZjk3ODVkMmJhYjVmNmVhNTU1OTBlNjM2ZGEwYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rN7WpJC8EkcvvedQ2HTeWtmCksPZuUpv8vvEe2TpAw4)

好的大佬我研究下

**Comment by AsherShelby** [comment]
我试着更改了一下，代码已经更新，你看看能不能用

**Comment by AsherShelby** [comment]
如果还是有问题的话，由于我这里的账号没有这种课程，所以如果可以的话发送一个可供测试的账号，我的邮箱asheron.e@qq.com

**Comment by LN-111** [comment]
> 我尝试更改一下，代码已经更新，你看看能不能用



> 我尝试更改一下，代码已经更新，你看看能不能用



> 如果还是有问题的话，由于我这里的账号没有课程，所以如果可以的话发送一个手动测试的账号，我的邮箱[asheron.e@qq.com](mailto:asheron.e@qq.com)

大佬我可以了我修改了下代码
![微信图片_20240517143130](https://github.com/AsherShelby/FuckingOnlineCourse/assets/85479940/3129f32c-cb3a-44ba-a980-3c663b5da520)

**Comment by LN-111** [comment]
> 如果还是有问题的话，由于我这里的账号没有课程，所以如果可以的话发送一个手动测试的账号，我的邮箱[asheron.e@qq.com](mailto:asheron.e@qq.com)

因为我第一页都没有能刷的我直接跳过去了

**Comment by LN-111** [comment]
> 如果还是有问题的话，由于我这里的账号没有课程，所以如果可以的话发送一个手动测试的账号，我的邮箱[asheron.e@qq.com](mailto:asheron.e@qq.com)

真的太谢谢你了

**Comment by cpcpisme** [comment]
运行不了呀，而且谷歌的没有130版本的驱动

**Comment by cpcpisme** [comment]
可以加您的微信吗

**Comment by wuna230521** [comment]
最新版下载地址  https://skzs.online  测试过了可用而且非常好用，不需要安装其它东西
